// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MyCompany.MyModule.Templates.StartupTemplate
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Docs\source_code\samples\create-new-decorator\MyModule\MyCompany.MyModule\Templates\StartupTemplate\StartupTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class StartupTemplate : IntentRoslynProjectItemTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nusing Intent.RoslynWeaver.Attributes;\r\nusing Microsoft.AspNetCore.Builder;\r\nusi" +
                    "ng Microsoft.AspNetCore.Hosting;\r\nusing Microsoft.Extensions.Configuration;\r\nusi" +
                    "ng Microsoft.Extensions.DependencyInjection;\r\n");
            
            #line 14 "C:\Dev\Intent.Docs\source_code\samples\create-new-decorator\MyModule\MyCompany.MyModule\Templates\StartupTemplate\StartupTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DependencyUsings));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)] // Overwrite this file on each S" +
                    "oftware Factory run.\r\n\r\nnamespace ");
            
            #line 18 "C:\Dev\Intent.Docs\source_code\samples\create-new-decorator\MyModule\MyCompany.MyModule\Templates\StartupTemplate\StartupTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 20 "C:\Dev\Intent.Docs\source_code\samples\create-new-decorator\MyModule\MyCompany.MyModule\Templates\StartupTemplate\StartupTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public ");
            
            #line 22 "C:\Dev\Intent.Docs\source_code\samples\create-new-decorator\MyModule\MyCompany.MyModule\Templates\StartupTemplate\StartupTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // [IntentManaged(Mode.Ignore)] // Uncomment to take over configuring services
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
        }

        // [IntentManaged(Mode.Ignore)] // Uncomment to take over configuring the HTTP request pipeline
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            ");
            
            #line 43 "C:\Dev\Intent.Docs\source_code\samples\create-new-decorator\MyModule\MyCompany.MyModule\Templates\StartupTemplate\StartupTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetConfigureCode()));
            
            #line default
            #line hidden
            this.Write("\r\n            app.UseMvc();\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
