// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MyCompany.MyModule.Templates.ControllerTemplate
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Services.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Temp\TestModule\MyModule\MyCompany.MyModule\Templates\ControllerTemplate\ControllerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ControllerTemplate : IntentRoslynProjectItemTemplateBase<IServiceModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nusing Intent.RoslynWeaver.Attributes;\r\nusing Microsoft.AspNetCore.Mvc;\r\n");
            
            #line 12 "C:\Temp\TestModule\MyModule\MyCompany.MyModule\Templates\ControllerTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DependencyUsings));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n[assembly: DefaultIntentManaged(Mode.Merge)] // Allowing additive updating of" +
                    " this file, while keeping user implementations\r\n\r\nnamespace ");
            
            #line 16 "C:\Temp\TestModule\MyModule\MyCompany.MyModule\Templates\ControllerTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    [Route(\"api/[controller]\")]\r\n    public class ");
            
            #line 19 "C:\Temp\TestModule\MyModule\MyCompany.MyModule\Templates\ControllerTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" : Controller\r\n    {\r\n\r\n");
            
            #line 22 "C:\Temp\TestModule\MyModule\MyCompany.MyModule\Templates\ControllerTemplate\ControllerTemplate.tt"
  foreach(var operation in Model.Operations) { 
            
            #line default
            #line hidden
            this.Write("        [HttpGet(\"[action]\")]\r\n        public IActionResult ");
            
            #line 24 "C:\Temp\TestModule\MyModule\MyCompany.MyModule\Templates\ControllerTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 24 "C:\Temp\TestModule\MyModule\MyCompany.MyModule\Templates\ControllerTemplate\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", operation.Parameters.Select(x => string.Format("{0} {1}", Types.Get(x.Type), x.Name)))));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return Ok(\"It\'s working!\");\r\n        }\r\n\r\n");
            
            #line 29 "C:\Temp\TestModule\MyModule\MyCompany.MyModule\Templates\ControllerTemplate\ControllerTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
